feat(navbar): navbar
paastech-cloud/website pull request #3
Opened 2023-06-17 15:33 UTC by thomas-mauran

## What does this PR do ?
<img width="1440" alt="Capture d’écran, le 2023-06-17 à 17 30 41" src="https://github.com/paas-tech/website/assets/78204354/c3882dbe-db74-4d8f-af37-a540f32dbf92">

This pr allows us to have a base for the navbar. For the moment the theme is not right, i didn't used the same font etc for the moment to do that in the theme pr 

### How should this be manually tested?

- Step 1 : clone and run

### Other changes

- adding a first letter uppercase helper
- adding an icon lib (fontawesome)

### Boyscout

2023-06-17 16:46 UTC, lapsus-ord commented
test depuis le cli :exploding_head:

2023-06-17 16:50 UTC, noetarbouriech requested changes

2023-06-17 16:50 UTC, noetarbouriech commented on src/assets/logo.png
Need to use the real logo

2023-06-17 22:53 UTC, lapsus-ord approved these changes

2023-06-18 09:25 UTC, thomas-mauran commented on src/assets/logo.png
I used an un copyrighted version for the moment since we didn't vote for the logo yet

2023-06-18 12:14 UTC, noetarbouriech approved these changes

2023-06-18 13:05 UTC, merged